scrape_configs:
  - job_name: 'prometheus'
    metrics_path: '/api/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets:
          - 'blue:8080'
          - 'green:8081'

  - job_name: 'node_exporter'
    static_configs:
      - targets: [ 'node-exporter:9100' ]
