version: '3.8'

services:
  blue:
    image: ands0927/yusin-quiz:latest
    container_name: green
    ports:
      - "8081:8081"
    environment:
      - PROFILES=green
      - ENV=greens
    networks:
      - quiz

networks:
  quiz:
    external: true
