version: '3.8'

services:
  blue:
    image: ands0927/yusin-quiz:latest
    container_name: blue
    ports:
      - "8080:8080"
    environment:
      - PROFILES=blue
      - ENV=blue
    networks:
      - quiz

networks:
  quiz:
    external: true
