package com.cpa.yusin.quiz.mock;

import com.cpa.yusin.quiz.subject.domain.SubjectStatus;
import com.cpa.yusin.quiz.subject.domain.Subject;
import com.cpa.yusin.quiz.subject.service.port.SubjectRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeSubjectRepository implements SubjectRepository
{
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Subject> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Subject save(Subject subject)
    {
        if(subject.getId() == null || subject.getId() == 0){
            Subject newSubject = Subject.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .name(subject.getName())
                    .status(subject.getStatus())
                    .isRemoved(subject.isRemoved())
                    .build();
            data.add(newSubject);
            return newSubject;
        } else{
          data.removeIf(item -> Objects.equals(item.getId(), subject.getId()));
          data.add(subject);
        }
        return subject;
    }

    @Override
    public Optional<Subject> findById(long id)
    {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public Optional<Subject> findPublishedById(long id)
    {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .filter(item -> !item.isRemoved())
                .filter(item -> item.getStatus() == SubjectStatus.PUBLISHED)
                .findAny();
    }

    @Override
    public List<Subject> findAll()
    {
        return data.stream()
                .filter(item -> !item.isRemoved())
                .sorted(Comparator.comparing(Subject::getName))
                .toList();
    }

    @Override
    public List<Subject> findAllPublished()
    {
        return data.stream()
                .filter(item -> !item.isRemoved())
                .filter(item -> item.getStatus() == SubjectStatus.PUBLISHED)
                .sorted(Comparator.comparing(Subject::getName))
                .toList();
    }


    @Override
    public boolean existsByName(String name)
    {
        return data.stream()
                .filter(item -> !item.isRemoved())
                .anyMatch(item -> item.getName().equals(name));
    }

    @Override
    public boolean existsByNameAndIdNot(long id, String name)
    {
        return data.stream()
                .filter(item -> !item.isRemoved())
                .anyMatch(item -> !item.getId().equals(id) && item.getName().equals(name));
    }

    @Override
    public Page<Subject> findAllOrderByName(Pageable pageable)
    {
        List<Subject> activeSubjects = findAll();
        List<Subject> result = activeSubjects.stream()
                .sorted(Comparator.comparing(Subject::getName))
                .limit(pageable.getPageSize())
                .skip(pageable.getOffset())
                .toList();

        return new PageImpl<>(result, pageable, activeSubjects.size());
    }

    @Override
    public Page<Subject> findAllPublishedOrderByName(Pageable pageable)
    {
        List<Subject> publishedSubjects = findAllPublished();
        List<Subject> result = publishedSubjects.stream()
                .limit(pageable.getPageSize())
                .skip(pageable.getOffset())
                .toList();

        return new PageImpl<>(result, pageable, publishedSubjects.size());
    }
}
