package com.cpa.yusin.quiz.mock;

import com.cpa.yusin.quiz.bookmark.domain.Bookmark;
import com.cpa.yusin.quiz.bookmark.service.port.BookmarkRepository;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Slice;
import org.springframework.data.domain.SliceImpl;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeBookmarkRepository implements BookmarkRepository {

    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Bookmark> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Bookmark save(Bookmark bookmark) {
        if (bookmark.getId() == null || bookmark.getId() == 0) {
            Bookmark newBookmark = Bookmark.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .member(bookmark.getMember())
                    .problem(bookmark.getProblem())
                    .build();
            data.add(newBookmark);
            return newBookmark;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), bookmark.getId()));
            data.add(bookmark);
            return bookmark;
        }
    }

    @Override
    public void deleteByMemberIdAndProblemId(Long memberId, Long problemId) {
        data.removeIf(b -> Objects.equals(b.getMember().getId(), memberId) &&
                Objects.equals(b.getProblem().getId(), problemId));
    }

    @Override
    public boolean existsByMemberIdAndProblemId(Long memberId, Long problemId) {
        return data.stream()
                .anyMatch(b -> Objects.equals(b.getMember().getId(), memberId) &&
                        Objects.equals(b.getProblem().getId(), problemId));
    }

    @Override
    public Optional<Bookmark> findByMemberIdAndProblemId(Long memberId, Long problemId) {
        return data.stream()
                .filter(b -> Objects.equals(b.getMember().getId(), memberId) &&
                        Objects.equals(b.getProblem().getId(), problemId))
                .findFirst();
    }

    @Override
    public Slice<Bookmark> findByMemberIdAndSubjectId(Long memberId, Long subjectId, Pageable pageable) {
        List<Bookmark> filtered = data.stream()
                .filter(b -> Objects.equals(b.getMember().getId(), memberId))
                .filter(b -> !b.getProblem().isRemoved())
                .filter(b -> subjectId == null ||
                        Objects.equals(b.getProblem().getExam().getSubjectId(), subjectId))
                .sorted(Comparator.comparing(Bookmark::getId).reversed()) // createdAt 대체 (Fake에서는 ID 순)
                .collect(Collectors.toList());

        int start = (int) pageable.getOffset();
        int end = Math.min(start + pageable.getPageSize(), filtered.size());

        if (start >= filtered.size()) {
            return new SliceImpl<>(Collections.emptyList(), pageable, false);
        }

        List<Bookmark> pageContent = filtered.subList(start, end);
        boolean hasNext = end < filtered.size();

        return new SliceImpl<>(pageContent, pageable, hasNext);
    }
}
