package com.cpa.yusin.quiz.mock;

import com.cpa.yusin.quiz.subscriptionPlan.domain.SubscriptionPlan;
import com.cpa.yusin.quiz.subscriptionPlan.service.port.SubscriptionPlanRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeSubscriptionPlanRepository implements SubscriptionPlanRepository
{
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<SubscriptionPlan> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public SubscriptionPlan save(SubscriptionPlan subscriptionPlan)
    {
        if (subscriptionPlan.getId() == null || subscriptionPlan.getId() == 0) {
            SubscriptionPlan newSubscriptionPlan = SubscriptionPlan.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .durationMonth(subscriptionPlan.getDurationMonth())
                    .price(subscriptionPlan.getPrice())
                    .build();
            data.add(newSubscriptionPlan);
            return newSubscriptionPlan;
        } else {
            data.removeIf(item -> Objects.equals(item.getId(), subscriptionPlan.getId()));
            data.add(subscriptionPlan);
        }

        return subscriptionPlan;
    }

    @Override
    public Optional<SubscriptionPlan> findById(Long id)
    {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public List<SubscriptionPlan> findAll()
    {
        return data.stream()
                .toList();
    }

    @Override
    public void deleteById(Long id)
    {
        data.removeIf(product -> Objects.equals(product.getId(), id));
    }

    @Override
    public boolean existsById(Long id)
    {
        return data.stream()
                .anyMatch(product -> Objects.equals(product.getId(), id));
    }

    @Override
    public boolean existsByDurationMonth(Integer durationMonth)
    {
        return data.stream()
                .anyMatch(product -> Objects.equals(product.getDurationMonth(), durationMonth));
    }

    @Override
    public boolean existsByDurationMonthAndIdNot(Integer durationMonth, Long id)
    {
        return data.stream()
                .anyMatch(product -> Objects.equals(product.getDurationMonth(), durationMonth)
                        && !Objects.equals(product.getId(), id));
    }
}
