package com.cpa.yusin.quiz.mock;

import com.cpa.yusin.quiz.problem.domain.Problem;
import com.cpa.yusin.quiz.problem.service.dto.AdminProblemLectureStatus;
import com.cpa.yusin.quiz.problem.service.dto.AdminProblemSearchCondition;
import com.cpa.yusin.quiz.problem.service.dto.AdminProblemSearchProjection;
import com.cpa.yusin.quiz.problem.service.dto.WordProblemCandidateProjection;
import com.cpa.yusin.quiz.problem.service.dto.WordProblemCountProjection;
import com.cpa.yusin.quiz.problem.service.port.ProblemRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.Pageable;
import org.springframework.util.StringUtils;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;
import java.util.stream.Collectors;

public class FakeProblemRepository implements ProblemRepository
{
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Problem> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Problem save(Problem problem)
    {
        if(problem.getId() == null || problem.getId() == 0){
            Problem newProblem = Problem.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .content(problem.getContent())
                    .explanation(problem.getExplanation())
                    .contentJson(problem.getContentJson())
                    .explanationJson(problem.getExplanationJson())
                    .number(problem.getNumber())
                    .isRemoved(problem.isRemoved())
                    .lectureYoutubeUrl(problem.getLectureYoutubeUrl())
                    .lectureStartSecond(problem.getLectureStartSecond())
                    .exam(problem.getExam())
                    .requiresCalculation(problem.isRequiresCalculation())
                    .build();

            data.add(newProblem);
            return newProblem;
        } else{
            data.removeIf(item -> Objects.equals(item.getId(), problem.getId()));
            data.add(problem);
        }
        return problem;
    }

    @Override
    public List<Problem> findAll()
    {
        return data;
    }

    @Override
    public List<Problem> findAllByExamId(long examId)
    {
        return data.stream()
                .filter(item -> item.getExam().getId().equals(examId))
                .filter(item -> !item.isRemoved())
                .toList();
    }

    @Override
    public Optional<Problem> findById(long id)
    {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }


    @Override
    public boolean existsByExamIdAndNumber(Long examId, int number)
    {
        return data.stream()
                .anyMatch(p -> p.getExam().getId().equals(examId)
                        && p.getNumber() == number
                        && !p.isRemoved());
    }

    @Override
    public Optional<Problem> findRemovedByExamIdAndNumber(long examId, int number) {
        return data.stream()
                .filter(problem -> problem.getExam().getId().equals(examId))
                .filter(problem -> problem.getNumber() == number)
                .filter(Problem::isRemoved)
                .findFirst();
    }

    @Override
    public Integer findMinimumNumberByExamId(long examId) {
        return data.stream()
                .filter(problem -> problem.getExam().getId().equals(examId))
                .map(Problem::getNumber)
                .min(Integer::compareTo)
                .orElse(null);
    }

    @Override
    public List<WordProblemCountProjection> countPublishedWordProblemsBySubject() {
        return data.stream()
                .filter(this::isPublishedWordProblem)
                .collect(Collectors.groupingBy(problem -> problem.getExam().getSubjectId(), Collectors.counting()))
                .entrySet().stream()
                .map(entry -> new WordProblemCountProjection(entry.getKey(), entry.getValue()))
                .toList();
    }

    @Override
    public List<WordProblemCandidateProjection> findPublishedWordProblemCandidatesBySubjectId(Long subjectId) {
        return data.stream()
                .filter(this::isPublishedWordProblem)
                .filter(problem -> Objects.equals(problem.getExam().getSubjectId(), subjectId))
                .sorted(Comparator.comparingInt((Problem problem) -> problem.getExam().getYear())
                        .thenComparing(problem -> problem.getExam().getId())
                        .thenComparing(Problem::getId))
                .map(problem -> new WordProblemCandidateProjection(
                        problem.getId(), problem.getExam().getId(), problem.getExam().getYear()))
                .toList();
    }

    /** 단위 테스트에서도 회차 batch 조회의 공개 말문제 필터를 재현한다. */
    @Override
    public List<Problem> findPublishedWordProblemsByIds(List<Long> problemIds) {
        Set<Long> ids = new HashSet<>(problemIds);
        return data.stream().filter(this::isPublishedWordProblem).filter(problem -> ids.contains(problem.getId())).toList();
    }

    private boolean isPublishedWordProblem(Problem problem) {
        return !problem.isRemoved()
                && !problem.isRequiresCalculation()
                && !problem.getExam().isRemoved()
                && problem.getExam().getStatus() == com.cpa.yusin.quiz.exam.domain.ExamStatus.PUBLISHED;
    }

    @Override
    public long countActiveByExamId(long examId) {
        return data.stream()
                .filter(problem -> problem.getExam().getId().equals(examId))
                .filter(problem -> !problem.isRemoved())
                .count();
    }

    @Override
    public Map<Long, Long> countActiveByExamIds(List<Long> examIds) {
        Set<Long> examIdSet = new HashSet<>(examIds);

        return data.stream()
                .filter(problem -> examIdSet.contains(problem.getExam().getId()))
                .filter(problem -> !problem.isRemoved())
                .collect(Collectors.groupingBy(problem -> problem.getExam().getId(), Collectors.counting()));
    }

    @Override
    public void flush() {
        // no-op
    }

    @Override
    public Page<AdminProblemSearchProjection> searchAdminProblems(Pageable pageable,
                                                                  AdminProblemSearchCondition searchCondition) {
        List<AdminProblemSearchProjection> filtered = data.stream()
                .filter(problem -> !problem.isRemoved())
                .filter(problem -> matchesLectureStatus(problem, searchCondition.lectureStatus()))
                .filter(problem -> searchCondition.subjectId() == null
                        || Objects.equals(problem.getExam().getSubjectId(), searchCondition.subjectId()))
                .filter(problem -> searchCondition.year() == null
                        || problem.getExam().getYear() == searchCondition.year())
                .filter(problem -> searchCondition.examId() == null
                        || Objects.equals(problem.getExam().getId(), searchCondition.examId()))
                .sorted(Comparator.comparing((Problem problem) -> problem.getExam().getYear()).reversed()
                        .thenComparing(problem -> problem.getExam().getId(), Comparator.reverseOrder())
                        .thenComparing(Problem::getNumber)
                        .thenComparing(Problem::getId))
                .map(problem -> new AdminProblemSearchProjection(
                        problem,
                        problem.getExam().getSubjectId(),
                        "subject",
                        problem.getExam().getId(),
                        problem.getExam().getName(),
                        problem.getExam().getYear(),
                        0L,
                        0L
                ))
                .toList();

        int startIndex = Math.toIntExact(pageable.getOffset());
        if (startIndex >= filtered.size()) {
            return new PageImpl<>(Collections.emptyList(), pageable, filtered.size());
        }

        int endIndex = Math.min(startIndex + pageable.getPageSize(), filtered.size());
        return new PageImpl<>(filtered.subList(startIndex, endIndex), pageable, filtered.size());
    }

    private boolean matchesLectureStatus(Problem problem, AdminProblemLectureStatus lectureStatus) {
        boolean hasLecture = StringUtils.hasText(problem.getLectureYoutubeUrl());

        return switch (lectureStatus) {
            case ALL -> true;
            case WITH_LECTURE -> hasLecture;
            case WITHOUT_LECTURE -> !hasLecture;
        };
    }
}
