package com.cpa.yusin.quiz.mock;

import com.cpa.yusin.quiz.problem.domain.Problem;
import com.cpa.yusin.quiz.problem.service.port.ProblemRepository;

import java.util.*;
import java.util.concurrent.atomic.AtomicLong;

public class FakeProblemRepository implements ProblemRepository
{
    private final AtomicLong autoGeneratedId = new AtomicLong(1);
    private final List<Problem> data = Collections.synchronizedList(new ArrayList<>());

    @Override
    public Problem save(Problem problem)
    {
        if(problem.getId() == null || problem.getId() == 0){
            Problem newProblem = Problem.builder()
                    .id(autoGeneratedId.getAndIncrement())
                    .content(problem.getContent())
                    .number(problem.getNumber())
                    .exam(problem.getExam())
                    .build();

            data.add(newProblem);
            return newProblem;
        } else{
            data.removeIf(item -> Objects.equals(item.getId(), problem.getId()));
            data.add(problem);
        }
        return problem;
    }

    @Override
    public List<Problem> saveAll(List<Problem> problems)
    {
        return problems.stream()
                .map(this::save)
                .toList();
    }

    @Override
    public List<Problem> findAllByExamId(long examId)
    {
        return data.stream()
                .filter(item -> item.getExam().getId().equals(examId))
                .toList();
    }

    @Override
    public Optional<Problem> findById(long id)
    {
        return data.stream()
                .filter(item -> item.getId().equals(id))
                .findAny();
    }

    @Override
    public void deleteById(long id)
    {
        data.removeIf(item -> item.getId().equals(id));
    }

    @Override
    public void deleteAllByIdInBatch(List<Long> ids)
    {
        data.removeIf(item -> ids.contains(item.getId()));
    }

    @Override
    public boolean existsById(long id)
    {
        return data.stream()
                .anyMatch(item -> item.getId().equals(id));
    }

    @Override
    public void deleteAllByExamId(long examId)
    {
        data.removeIf(item -> item.getExam().getId().equals(examId));
    }

    @Override
    public void deleteAllBySubjectId(long subjectId)
    {
        data.removeIf(item -> item.getExam().getSubjectId().equals(subjectId));
    }

    @Override
    public boolean existsByExamIdAndNumber(Long examId, int number)
    {
        return false;
    }
}
